[Config]
Dependencies=
Dependencies=base

[Output]
ImageId=snowfield
Output=snowfield
ManifestFormat=json

[Include]
# bootc deployment runtime
Include=%D/shared/packages/bootc/mkosi.conf
# snow payload composition (tree, scripts, packages)
Include=%D/shared/composition/snow/mkosi.conf
# surface kernel
Include=%D/shared/kernel/surface/mkosi.conf
# Image Output
Include=%D/shared/outformat/image/mkosi.conf
