[Config]
Dependencies=base

[Output]
ImageId=vscode
Output=vscode
Overlay=yes
ManifestFormat=json
Format=sysext

[Content]
Bootable=no
BaseTrees=%O/base
# Adds inode/directory to code.desktop's MimeType
PostInstallationScripts=%D/shared/packages/vscode/mkosi.postinst.d/vscode.chroot
PostOutputScripts=%D/shared/sysext/postoutput/sysext-postoutput.sh
FinalizeScripts=%D/shared/sysext/finalize/sysext-required-paths.sh,%D/shared/sysext/finalize/sysext-strip-icon-cache.sh

# Visual Studio Code (from packages.microsoft.com/repos/code in mkosi.sandbox)
Packages=code

[Build]
Environment=KEYPACKAGE=code
