[Config]
Dependencies=base

[Output]
ImageId=debdev
Output=debdev
Overlay=yes
ManifestFormat=json
Format=sysext

[Content]
Bootable=no
BaseTrees=%O/base
PostOutputScripts=%D/shared/sysext/postoutput/sysext-postoutput.sh
FinalizeScripts=%D/shared/sysext/finalize/sysext-required-paths.sh,%D/shared/sysext/finalize/sysext-strip-icon-cache.sh

Packages=debootstrap
    distro-info
    wget
    arch-test
    debian-archive-keyring
    mount
    binutils
    ubuntu-archive-keyring

[Build]
Environment=KEYPACKAGE=debootstrap
