[Config]
Dependencies=base

[Output]
ImageId=microsoft-identity-broker
Output=microsoft-identity-broker
Overlay=yes
ManifestFormat=json
Format=sysext

[Content]
Bootable=no
BaseTrees=%O/base
PostOutputScripts=%D/shared/sysext/postoutput/sysext-postoutput.sh
Environment=KEYPACKAGE=microsoft-identity-broker
