[Config]
Dependencies=
Dependencies=base

[Output]
ManifestFormat=json
ImageId=cayo
Output=cayo

[Include]
# bootc deployment runtime
Include=%D/shared/packages/bootc/mkosi.conf
# cayo payload composition (tree, scripts, packages)
Include=%D/shared/composition/cayo/mkosi.conf
# backports kernel
Include=%D/shared/kernel/backports/mkosi.conf
# Image Output
Include=%D/shared/outformat/image/mkosi.conf
