[Config]
Dependencies=base

[Output]
ImageId=sunshine
Output=sunshine
Overlay=yes
ManifestFormat=json
Format=sysext

[Content]
Bootable=no
BaseTrees=%O/base
PostOutputScripts=%D/shared/sysext/postoutput/sysext-postoutput.sh
FinalizeScripts=%D/shared/sysext/finalize/sysext-required-paths.sh,%D/shared/sysext/finalize/sysext-usr-only.sh,%D/shared/sysext/finalize/sysext-strip-icon-cache.sh
Packages=debianutils
         libcap2
         libcurl4t64
         libdrm2
         libevdev2
         libgbm1
         libglib2.0-0t64
         libgtk-3-0t64
         libayatana-appindicator3-1
         libicu76
         libminiupnpc18
         libnotify4
         libnuma1
         libopus0
         libpipewire-0.3-0t64
         libpulse0
         libssl3t64
         libva2
         libva-drm2
         libvulkan1
         libwayland-client0
         libx11-6
         miniupnpc

[Build]
Environment=KEYPACKAGE=sunshine
