#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Phase 7 publication step 1 (docs/native-ab-contracts.md §4/§5, plan
# "Atomic Publication Procedure" steps 4-6): uploads every immutable
# versioned object a prepare-native-publication.sh run produced to a
# candidate staging location under DEST, and records the intended
# Cache-Control on payload objects (public, max-age=31536000, immutable --
# these object names embed a partition UUID or are otherwise version-frozen,
# so they never change content once published).
#
# This step is intentionally NOT the final publish: objects land under a
# per-version candidate sub-path, never under the frozen public names
# directly, so a failed/partial candidate upload can never be mistaken for a
# real publication. verify-remote.sh checks candidate objects next;
# promote.sh (Phase 7 step 8+) copies verified candidate objects to their
# final names and signs the index.
#
# Neither the local, per-run unsigned SHA256SUMS nor publication-info.json
# are uploaded -- SHA256SUMS is regenerated by promote.sh over re-downloaded
# bytes (never trusted from local disk, docs/native-ab-contracts.md's
# "Atomic Publication Procedure" step 9), and publication-info.json is a
# local pipeline-only record with no place in the public namespace.
#
# Usage: publish-candidate.sh <prepared-dir> <dest>
#
#   prepared-dir  a prepare-native-publication.sh --xz output directory for
#                 ONE product, i.e. "<publish-out>/<product>/x86-64"
#                 (contains publication-info.json + SHA256SUMS + the
#                 immutable versioned objects for one version).
#   dest          publication origin root: a local directory (rehearsal) or
#                 "rclone:<remote>:<bucket>[/prefix]" (real remote). See
#                 publish-lib.sh's header for the exact addressing rules.
set -euo pipefail

usage() {
    echo "Usage: $0 <prepared-dir> <dest>" >&2
    exit 2
}

[[ "${1:-}" != "-h" && "${1:-}" != "--help" ]] || usage

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=shared/native-ab/publish/publish-lib.sh
source "$SCRIPT_DIR/publish-lib.sh"

[[ $# -eq 2 ]] || usage
PREPARED_DIR="$1"
DEST="$2"

for command in jq sha256sum; do
    command -v "$command" >/dev/null || { echo "Error: required command not found: $command" >&2; exit 1; }
done
[[ -d "$PREPARED_DIR" ]] || { echo "Error: prepared-dir not found: $PREPARED_DIR" >&2; exit 1; }
PREPARED_DIR="$(cd "$PREPARED_DIR" && pwd)"

read_publication_info "$PREPARED_DIR"
echo "Product: $PUB_PRODUCT  Channel: $PUB_CHANNEL  Version: $PUB_VERSION"

# ---------------------------------------------------------------------------
# Sweep stray *.tmp files (the "parked 3.3 note": prepare-native-
# publication.sh's own atomic-write scheme should never leave one behind on
# a successful run, but a killed/crashed prepare run could -- refuse to
# upload a directory that still has one, rather than silently skipping it or
# accidentally uploading a partial file).
# ---------------------------------------------------------------------------

mapfile -t stray_tmpfiles < <(find "$PREPARED_DIR" -maxdepth 1 -name '*.tmp' -o -name '*.tmp.*' 2>/dev/null)
if [[ ${#stray_tmpfiles[@]} -gt 0 ]]; then
    echo "Error: prepared-dir has leftover temp files from an interrupted prepare run:" >&2
    printf '  %s\n' "${stray_tmpfiles[@]}" >&2
    exit 1
fi

dest_parse "$DEST"
product_dir="$PUB_DEST_PATH"
candidate_dir="$product_dir/$(candidate_subpath "$PUB_VERSION")"

echo "Uploading candidate objects to $DEST -> $candidate_dir/"

count=0
while IFS= read -r name; do
    [[ -n "$name" ]] || continue
    src="$PREPARED_DIR/$name"
    [[ -f "$src" ]] || { echo "Error: SHA256SUMS lists '$name' but it is not present in $PREPARED_DIR" >&2; exit 1; }
    echo "  $name ($(du -h "$src" | cut -f1))"
    dest_put_file "$src" "$candidate_dir/$name" "public, max-age=31536000, immutable"
    count=$((count + 1))
done < <(candidate_object_names "$PREPARED_DIR")

[[ "$count" -gt 0 ]] || { echo "Error: SHA256SUMS in $PREPARED_DIR lists no objects" >&2; exit 1; }

echo "Published $count candidate object(s) for $PUB_CHANNEL $PUB_VERSION"
