[Config]
Dependencies=base

[Output]
ImageId=himmelblau
Output=himmelblau
Overlay=yes
ManifestFormat=json
Format=sysext

[Content]
Bootable=no
BaseTrees=%O/base
PostOutputScripts=%D/shared/sysext/postoutput/sysext-postoutput.sh
Environment=KEYPACKAGE=himmelblau

# Himmelblau Entra ID authentication (from himmelblau-idm.org nightly repo)
Packages=himmelblau
         pam-himmelblau
         nss-himmelblau
