[Config]
Dependencies=
Dependencies=base

[Output]
ManifestFormat=json
ImageId=cayo
Output=cayo-ab

[Content]
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
Packages=systemd-boot-efi
ExtraTrees=%D/shared/cayo/tree
PostInstallationScripts=%D/shared/kernel/scripts/postinst/mkosi.postinst.chroot
PostInstallationScripts=%D/shared/cayo/scripts/postinstall/cayo.postinst.chroot
FinalizeScripts=%D/shared/outformat/image/finalize/mkosi.finalize.chroot

[Include]
Include=%D/shared/packages/cayo/mkosi.conf
Include=%D/shared/kernel/backports/mkosi.conf
Include=%D/shared/outformat/ab-root/mkosi.conf
