/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5b5af1d7a3f7ea7e785d66d35014045e)
interface __BaseEnv_Env {
	REPOSITORY: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
